// Generated by https://quicktype.io

export type PokemonList = {
  count: number
  next: string
  previous: null
  results: BasePokemonInfo[]
}

export type BasePokemonInfo = {
  name: string
  url: string
}

export type SmallPokemon = {
  id: number | string
  name: string
}
